SELECT CATEGORY, T2.PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT T1
JOIN (SELECT MAX(PRICE) AS PRICE FROM FOOD_PRODUCT GROUP BY CATEGORY) T2 ON T1.PRICE = T2.PRICE
WHERE CATEGORY IN ('과자', '국','김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC