WITH TRUCK_INFO AS (
    SELECT 
        T1.CAR_ID,
        T2.HISTORY_ID,
        T1.CAR_TYPE,
        T1.DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE)+1 AS DURATION,
        (CASE
         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN "90일 이상"
         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN "30일 이상"
         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN "7일 이상"
         ELSE NULL
         END
        ) AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR AS T1
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T2
    ON T1.CAR_ID = T2.CAR_ID
    WHERE T1.CAR_TYPE = '트럭'
), PLAN AS (
    SELECT DURATION_TYPE, (100 - DISCOUNT_RATE) / 100 AS RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)


SELECT HISTORY_ID, FLOOR(DAILY_FEE * DURATION * RATE) AS FEE
FROM
(
    SELECT 
        CAR_ID,
        HISTORY_ID,
        DAILY_FEE,
        DURATION,
        IFNULL(RATE, 1) AS RATE
    FROM TRUCK_INFO AS INFO
    LEFT JOIN PLAN
    ON PLAN.DURATION_TYPE = INFO.DURATION_TYPE
) AS RESULT
ORDER BY FEE DESC, HISTORY_ID DESC