-- 2021년에 가입한 전체 회원수
SET @TOTAL = (SELECT COUNT(DISTINCT(USER_ID)) FROM USER_INFO WHERE YEAR(JOINED)=2021);

-- 2021년에 가입한 회원 ID
WITH USER_ID_TABLE AS(
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

-- 풀이
SELECT
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT(O.USER_ID)) AS PUCHASED_USERS,
    ROUND((COUNT(DISTINCT(O.USER_ID)) / @TOTAL), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
JOIN USER_ID_TABLE AS U
ON O.USER_ID = U.USER_ID
WHERE O.SALES_AMOUNT >= 1
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC