SELECT
    A.APNT_NO AS APNT_NO,
    P.PT_NAME AS PT_NAME,
    P.PT_NO AS PT_NO,
    A.MCDP_CD AS MCDP_CD,
    D.DR_NAME AS DR_NAME,
    A.APNT_YMD AS APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT AS P ON P.PT_NO = A.PT_NO
JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID
WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
    AND A.MCDP_CD = 'CS'
    AND A.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC