-- JOIN을 사용한 풀이
SELECT WRITER_ID,
       NICKNAME,
       CONCAT_WS(' ',CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS '전체주소',
       CONCAT_WS('-', LEFT(TLNO, 3), MID(TLNO,4, 4), RIGHT(TLNO, 4)) As '전화번호'
FROM USED_GOODS_BOARD AS BOARD
JOIN USED_GOODS_USER AS USER
ON BOARD.WRITER_ID = USER.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY WRITER_ID DESC

-- WITH를 사용한 풀이
WITH COUNT3 AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >=3
)

SELECT WRITER_ID,
       NICKNAME,
       CONCAT_WS(' ',CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS '전체주소',
       CONCAT_WS('-', LEFT(TLNO, 3), MID(TLNO,4, 4), RIGHT(TLNO, 4)) As '전화번호'
FROM COUNT3
JOIN USED_GOODS_USER AS USER
ON COUNT3.WRITER_ID = USER.USER_ID
ORDER BY WRITER_ID DESC