SELECT T2.MEMBER_NAME, T1.REVIEW_TEXT, DATE_FORMAT(T1.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS T1
JOIN
    (SELECT R.MEMBER_ID AS MEMBER_ID, M.MEMBER_NAME AS MEMBER_NAME
    FROM REST_REVIEW AS R
    JOIN MEMBER_PROFILE AS M
    ON R.MEMBER_ID = M.MEMBER_ID
    GROUP BY MEMBER_ID
    ORDER BY COUNT(R.REVIEW_TEXT) DESC
    LIMIT 1) T2
ON T1.MEMBER_ID= T2.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC