SELECT 
    MONTH(T1.START_DATE) AS MONTH,
    T1.CAR_ID AS CAR_ID,
    COUNT(T1.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T1
JOIN (SELECT CAR_ID, COUNT(CAR_ID) AS CAR_CNT
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
      GROUP BY CAR_ID
      HAVING CAR_CNT >= 5) AS T2
ON T1.CAR_ID = T2.CAR_ID
WHERE YEAR(T1.START_DATE) = 2022 AND MONTH(T1.START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH(T1.START_DATE), T1.CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC